#interface table
SELECT ID, ACTIVE, CLSNM, INFNM, INFDRPT, INFURL, INFMETHOD, INFTYP, RETURNDTONM, MEMO, VERSION
FROM jw_platform.IFD_INTERFACEDEF;
desc jw_platform.IFD_INTERFACEDEF;

#interface->case table
SELECT ID, ACTIVE, CLSNM, INFNM, EXAMPLENM, EXAMPLETYP, MEMO, VERSION, CREATED_BY_ID, CREATED_BY_CODE, CREATED_BY, CREATED_DATE, MODIFIED_BY_ID, MODIFIED_BY_CODE, MODIFIED_BY, MODIFIED_DATE
FROM jw_platform.IFD_EXAMPLEDEF;
desc jw_platform.IFD_EXAMPLEDEF;

#interface->case->args input table
SELECT ID, EXAMPLEDEF_ID, PARAMNM, VALUE, VERSION, CREATED_BY_ID, CREATED_BY_CODE, CREATED_BY, CREATED_DATE, MODIFIED_BY_ID, MODIFIED_BY_CODE, MODIFIED_BY, MODIFIED_DATE
FROM jw_platform.IFD_EXPINPUT;
desc jw_platform.IFD_EXPINPUT;

#interface->case->args output table
SELECT ID, EXAMPLEDEF_ID, RETURNVALUE, VERSION, CREATED_BY_ID, CREATED_BY_CODE, CREATED_BY, CREATED_DATE, MODIFIED_BY_ID, MODIFIED_BY_CODE, MODIFIED_BY, MODIFIED_DATE
FROM jw_platform.IFD_EXPOUTPUT;
desc jw_platform.IFD_EXPOUTPUT;

#interface->case->args assert table
SELECT ID, ACTIVE, EXAMPLEDEF_ID, SCRIPT, VERSION, CREATED_BY_ID, CREATED_BY_CODE, CREATED_BY, CREATED_DATE, MODIFIED_BY_ID, MODIFIED_BY_CODE, MODIFIED_BY, MODIFIED_DATE
FROM jw_platform.IFD_EXPASSERT;
desc jw_platform.IFD_EXPASSERT;


--------------------------------------------------------------------------
CREATE TABLE `IFD_INTERFACEDEF` (
  `ID` int(12) NOT NULL AUTO_INCREMENT,
  `ACTIVE` varchar(1) DEFAULT NULL,
  `CLSNM` varchar(200) DEFAULT NULL,
  `INFNM` varchar(100) DEFAULT NULL,
  `INFDRPT` varchar(200) DEFAULT NULL,
  `INFURL` varchar(200) DEFAULT NULL,
  `INFMETHOD` varchar(20) DEFAULT NULL,
  `INFTYP` varchar(20) DEFAULT NULL,
  `RETURNDTONM` varchar(200) DEFAULT NULL,
  `MEMO` varchar(500) DEFAULT NULL,
  `VERSION` int(10) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;

CREATE TABLE `IFD_EXAMPLEDEF` (
  `ID` int(12) NOT NULL AUTO_INCREMENT,
  `ACTIVE` varchar(1) DEFAULT NULL,
  `CLSNM` varchar(200) DEFAULT NULL,
  `INFNM` varchar(100) DEFAULT NULL,
  `EXAMPLENM` varchar(200) DEFAULT NULL,
  `EXAMPLETYP` varchar(1) DEFAULT NULL,
  `MEMO` varchar(500) DEFAULT NULL,
  `VERSION` int(10) DEFAULT NULL,
  `CREATED_BY_ID` varchar(50) DEFAULT NULL,
  `CREATED_BY_CODE` varchar(100) DEFAULT NULL,
  `CREATED_BY` varchar(50) DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `MODIFIED_BY_ID` varchar(50) DEFAULT NULL,
  `MODIFIED_BY_CODE` varchar(100) DEFAULT NULL,
  `MODIFIED_BY` varchar(50) DEFAULT NULL,
  `MODIFIED_DATE` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `IFD_EXPASSERT` (
  `ID` int(12) NOT NULL AUTO_INCREMENT,
  `ACTIVE` varchar(1) DEFAULT NULL,
  `EXAMPLEDEF_ID` int(13) DEFAULT NULL,
  `SCRIPT` text,
  `VERSION` int(10) DEFAULT NULL,
  `CREATED_BY_ID` varchar(50) DEFAULT NULL,
  `CREATED_BY_CODE` varchar(100) DEFAULT NULL,
  `CREATED_BY` varchar(50) DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `MODIFIED_BY_ID` varchar(50) DEFAULT NULL,
  `MODIFIED_BY_CODE` varchar(100) DEFAULT NULL,
  `MODIFIED_BY` varchar(50) DEFAULT NULL,
  `MODIFIED_DATE` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;

CREATE TABLE `IFD_EXPINPUT` (
  `ID` int(12) NOT NULL AUTO_INCREMENT,
  `EXAMPLEDEF_ID` int(13) DEFAULT NULL,
  `PARAMNM` int(15) DEFAULT NULL,
  `VALUE` text,
  `VERSION` int(10) DEFAULT NULL,
  `CREATED_BY_ID` varchar(50) DEFAULT NULL,
  `CREATED_BY_CODE` varchar(100) DEFAULT NULL,
  `CREATED_BY` varchar(50) DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `MODIFIED_BY_ID` varchar(50) DEFAULT NULL,
  `MODIFIED_BY_CODE` varchar(100) DEFAULT NULL,
  `MODIFIED_BY` varchar(50) DEFAULT NULL,
  `MODIFIED_DATE` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `IFD_EXPOUTPUT` (
  `ID` int(12) NOT NULL AUTO_INCREMENT,
  `EXAMPLEDEF_ID` int(13) DEFAULT NULL,
  `RETURNVALUE` text,
  `VERSION` int(10) DEFAULT NULL,
  `CREATED_BY_ID` varchar(50) DEFAULT NULL,
  `CREATED_BY_CODE` varchar(100) DEFAULT NULL,
  `CREATED_BY` varchar(50) DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `MODIFIED_BY_ID` varchar(50) DEFAULT NULL,
  `MODIFIED_BY_CODE` varchar(100) DEFAULT NULL,
  `MODIFIED_BY` varchar(50) DEFAULT NULL,
  `MODIFIED_DATE` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
